# example config
paths:
  processed_data: "./processed_data"
  results: "./results"

network_layers: "network_layers.csv"
hazard_layers: "hazard_layers.csv"

extract_bbox:
  left: 760000
  bottom: 640000
  right: 780000
  top: 660000
