configfile: "config.json"

import pandas as pd
import geopandas as gpd
import os

HAZARD_TYPES = (
    "TC",
    "flooding",
)
PARAMETER_SET_IDS = range(13)

# assign globals to these paths, they're used frequently
RAW = config["paths"]["incoming_data"]
DATA = config["paths"]["data"]
OUTPUT = config["paths"]["output"]  # We use a wildcard for this instead

wildcard_constraints:
    hazard="[^_/]+",  # no slash or underscore
    gpkg="[^/]+",  # no slash in filename
    protection_type="[^/]+",  # no slash
    layer="(nodes|edges|areas)",
    threshold="\d+(p\d+)?",
    output_path=f"{OUTPUT}(/.+[^/])?",
    parameter_set="parameter_set_\d+",

# container: "docker://nismod/jamaica-infrastructure"
# container: "docker://geo-test"

include: "_damage.smk"
include: "_criticality.smk"
include: "_losses.smk"
include: "_adaptation.smk"
include: "_etl.smk"

# include: "losses.smk"
# include: "direct_damages.smk"
# include: "transport_model.smk"
# include: "hotspots.smk"

from check_targets import EXPOSURE, DAMAGES, LOSSES, EAD_EAEL, TARGETS

rule all_exposure:
    input: EXPOSURE

rule all_damages:
    input: DAMAGES

rule all_losses:
    input: LOSSES

rule all_ead_eael:
    input: EAD_EAEL

rule all_targets:
    input: TARGETS
