configfile: "config.json"

# assign globals to these paths, they're used frequently
DATA = config["paths"]["data"]
OUTPUT = config["paths"]["output"]

include: "direct_damages.smk"
include: "losses.smk"
include: "transport_model.smk"