# This file contains configuration options for jamaica-infrastructure analyses.
#
# These values are used by snakemake rules and Python scripts located in the
# `workflow/` directory.

### FILE AND DIRECTORY LOCATIONS ###
# Paths on disk required directories and files
# The contents of incoming_data and data are required to run an analysis
# TODO: Rationalise the IO directories
paths:
  # Location of some input data (road network from open-gira)
  incoming_data: "incoming_data"
  # Principally input data (but also some outputs)
  data: "processed_data"
  # Location of most intermediate analyses and output results
  output: "results"
  # Metadata table of hazard raster attributes and locations
  hazard_layers: "workflow/hazard_layers.csv"
  # Metadata table of infrastructure assets, one row per asset class (e.g. road segments,
  # ports, electricity transmission lines etc.)
  network_layers: "workflow/network_layers_hazard_intersections_details.csv"

### DAMAGES ###
# The direct damages step attempts to calculate a likely rebuild/rehabilitation
# cost for assets experiencing hazards at given return periods. Expected Annual
# Damages (EAD) are also computed.
#
# Pertaining to direct damages to assets
damages:
  # Flooding return period that bridges are assumed to withstand without damage
  bridge_flood_design_RP_years: 50
  # Transport network rehabilitation costs
  rehabilitation_costs:
    bridge_cost_USD_per_meter: 15000.0
    road_cost_USD_per_lane_per_km: 750000.0
#
# Whether to run a sensitivity analysis over rehabilitation costs and fragility
# of assets. If true, direct damages will be calculated for several ensemble
# members. Results will be present for min/mean/max aggregations of these members.
#
# See `workflow/_damage.smk`, rule sensitivity_parameters for more information.
sensitivity_analysis: true

### ROAD NETWORK GENERATION ###
# The road (and therefore the multi-modal) transport network is derived from an
# OpenStreetMap extract, created with the nismod/open-gira repository.
road_classification:
  # The OpenStreetMap derived road network comes with a 'highway' tag that
  # contains information about what kind of road any given segment is.
  # We make an informed guess at the mapping from OpenStreetMap highway
  # classification to the Government of Jamaicas. This will not be perfect.
  OSM_to_NWA:
    motorway: "MOTORWAY"
    trunk: "CLASS A"
    primary: "CLASS A"
    secondary: "CLASS B"
    tertiary: "CLASS C"
    residential: "RESIDENTIAL"
    unclassified: "UNCLASSIFIED"
  # Any OpenStreetMap highway tag value that is not listed in `OSM_to_NWA`
  # will be given this value.
  default_NWA: "UNCLASSIFIED"

  # The OpenStreetMap highway tag is also used to select appropriate damage
  # curves. The mapping is configurable here. Damage curves keyed on the values
  # below are located in the damage_curves directory.
  OSM_to_damage_curve:
    bridge: "road_bridge"
    motorway: "road_paved"
    primary: "road_paved"
    residential: "road_paved"
    secondary: "road_paved"
    tertiary: "road_paved"
    trunk: "road_paved"
    unclassified: "road_unpaved"

### ECONOMICS ###
economics:
  # Exchange rate to use when converting rehabilitation costs, losses, etc.
  USD_per_JMD: 0.0064
  # Labour cost, used to put a value on disruption cost of labour rerouting
  # Average wage is 200~500 JMD for 2012 stats, with a 45.4% inflation in currency
  # 0.4 * (1 + 0.454) * 235.25 = 136.82
  labour_cost_JMD_per_hour: 136.82
  # Multiplied by additional rerouting time and trade value to find a lost value of trade
  disrupted_trade_fraction: 0.02

### CRITICALITY ###
# The transport criticality analysis removes single links from the network and
# quantifies how this affects trade and labour flows.
#
# The transport network is processed in chunks. This option defines the number
# of chunks. Rules may be invoked in parallel to operate on multiple chunks
# simulatenously.
#
# See `workflow/_criticality.smk`, specifically rules `transport_scenario_edge_map`
# and `single_point_failure_road_rail` for more details.
single_link_failure_chunk_count: 128

### HOTSPOTS ###
# The hotspots analyses identify which areas are critical for transport network
# performance.
#
# We first define a grid.
# Then, remove all assets within a grid cell from the network, then quantify the
# reduction in network performance. This is repeated for all grid cells. The
# output is optionally smoothed using Kernel Density Estimation.
# We can also identify the monetary value of assets within each cell (exposure
# value), for every sector.
hotspots:
  # Defining the raster grid to perform a hotspots analysis on. This is the grid
  # on which assets are removed, cell-by-cell from.
  grid:
    # Buffer around bounding box of Jamaican coastline in meters
    boundary_buffer_meters: 10000
    # Width and heght of grid cells in meters
    resolution_meters: 2500
  # Options for applying a smoothing Gaussian kernel process to economic loss
  # hotspots in transport sector
  kernel_density_estimation:
    # Measure of width Gaussian kernel
    bandwidth_meters: 1500
    # Resolution of grid to evaluate sum of Gaussian kernels (typically finer
    # than above grid)
    resolution_meters: 500
#
# N.B. There is a distinct hotspots analysis available for the energy network
# in the nismod/JEM repository.

### ADAPTATION OPTIONS ###
# We explore a variety of per-asset adaptation options to mitigate the effects
# of hazards.
#
# These interventions may avoid damage and loss, but they will require initial
# investment. The entries below are the configurable financial parameters of
# the adaptation options.
adaptation_options:
  # Starting year of economic modelling for adaptation options
  baseline_year: 2019
  # End year of economic modelling for adaptation options
  projection_end_year: 2100
  # Annually applied percentage rate to discount future values in economic modelling
  discounting_rate: 10
  # TODO: Store this in src/constants.py or similar, it should not be configurable
  epsg_jamaica: 3448
  # Flood defence heights to consider for relevant adaptation options
  flood_thresholds_meters: [1.0, 1.5, 2.0, 2.5]
  # When considering adaptation to TC winds, a factor, let it be known as u, is
  # used to modify damage curves of adapted assets. A damage curve is damage
  # fraction as a function of hazard intensity, say d(h). The damage fraction
  # modified by u is: d(h) * (1 - u)
  # For example, for a value of 0.76, d(h) * (1 - 0.76) = 0.24d(h), so the
  # damage curve is squashed roughly by a factor 4.
  TC_winds_damage_curve_squash: [0.76]
  # Expected Annual Economic Loss (EAEL) figures are calculated in J$/day. To
  # compute the wider economic loss arising from a disruption, one must multiply
  # by an assumed disruption duration.
  disruption_duration_days: 15

### COASTAL ADAPTATION ###
# This section defines parameters used in generating the coastal flood protection 
# areas and coastal revetment segments used in evaluating coastal adaptation options 
# to mitigate the coastal flooding hazard along the coastline.
coastal_adaptation: 
  # Inland buffer distance (in kilometers) used to define the initial inland extent
  # of the flood impact areas from the coastline. 
  inland_buffer: 2
  # Flood depth threshold (in meters) above which areas are considered to be
  # affected by coastal flooding. Used to delineate flood hazard zones.
  flood_threshold: 0.1
  # DBSCAN clustering epsilon parameter. Defines the maximum distance
  # between points in a cluster. Used to group flooding into flood areas.
  eps: 3
  # Minimum number of points required to form a DBSCAN cluster.
  minpts: 5
  # Maximum length (in meters) of each individual coastline segment for which an
  # adaptation (e.g. revetments) can be planned.
  coast_length: 5000
  # Fractional overlap between adjacent coastal flood areas to ensure coverage
  # and continuity of protection, and to prevent duplicated efforts in 
  # protecting assets within the flood protection areas.
  overlap: 0.50
    