"""Prepare building footprints with attributes for allocation to economic sectors.
"""

rule download_osm_jamaica:
    """Download country extract
    """
    output:
        pbf = f"{RAW}/osm/jamaica-{config["context"]["osm_extract_date"]}.osm.pbf",
    shell:
        """
        extract_dir=$(dirname {output.pbf})
        extract_date={config[context][osm_extract_date]}

        pushd $extract_dir

            # download extract
            wget http://download.geofabrik.de/central-america/jamaica-${{extract_date}}.osm.pbf
            wget http://download.geofabrik.de/central-america/jamaica-${{extract_date}}.osm.pbf.md5

            # check extract
            md5sum --check jamaica-${{extract_date}}.osm.pbf.md5

        popd
        """


rule filter_osm_buildings:
    """Filter OpenStreetMap extract for all buildings in Jamaica
    """
    input:
        pbf = f"{RAW}/osm/jamaica-{config["context"]["osm_extract_date"]}.osm.pbf",
    output:
        pbf = f"{DATA}/buildings/jamaica-buildings.osm.pbf",
        gpkg = f"{DATA}/buildings/jamaica-buildings.gpkg",
    shell:
        """
        osmium tags-filter \
            {input.pbf} \
            wnr/building \
            --overwrite \
            -o {output.pbf}

        # Extract features from .osm.pbf to .gpkg
        OSM_CONFIG_FILE=workflow/1_context/osmconf.ini ogr2ogr -f GPKG \
            {output.gpkg} \
            {output.pbf} \
            multipolygons
        """

rule building_height_assignments:
    """
    """
    input:
        script = "workflow/1_context/building_height_assignments.py",
        # It also needs the below script to exist to run a subprocess, not sure if that would be stated as an input or param or not at all
        vector_raster_intersections_script = "workflow/1_context/vector_raster_intersections.py",
        building_layers = f"{DATA}/buildings/building_layers.csv",
        building_rasters = f"{DATA}/buildings/building_rasters.csv",
        buildings_econ_activity = f"{DATA}/buildings/buildings_assigned_economic_activity.gpkg"
    output:
        results = f"{OUTPUT}/buildings_heights/buildings_heights.gpkg"
    shell:
        """
        python {input.script} \
            --data-dir {DATA} \
            --output-dir {OUTPUT} \
            --vector-raster-intersections-script {input.vector_raster_intersections_script} \
            --building-layers {input.building_layers} \
            --building-rasters {input.building_rasters} \
            --buildings-econ-activity {input.buildings_econ_activity} 
        """

# rule building_data_process:
#     """
#     """
#     input: 
#         script = "workflow/1_context/buildings_data_process.py",
#         poi_data = f"{RAW}/hotosm_data/hotosm_jam_points_of_interest_gpkg/buildings_assigned_economic_sectors_intermediate.gpkg",
#         poi_mapping = f"{RAW}/hotosm_data/hotosm_jam_points_of_interest_gpkg/hotosm_mapping_economic_sectors.xlsx",
#         buildings_input_map = f"{RAW}/buildings/osm_building_column_mapping_economic_sectors.xlsx",
#         buildings_input = f"{RAW}/buildings/jamaica-buildings.gpkg",
#         landuse_planing_layers = f"{"RAW"}/buildings/landuse_planning_layers_with_sectors.gpkg", #generated by panning_layers script
#         landuse_types = f"{DATA}/land_type_and_use/jamaica_land_use_combined.gpkg", #generated by land_use_layers_process script
#         landuse_types_with_sectors =f"{DATA}/land_type_and_use/jamaica_land_use_combined_with_sectors.gpkg", #generated by land_use_layers_process script
#         commercial_buildings = f"{RAW}/JAM_classified_buildings_industries/JAM_classified_buildings.shp",
#         nsdmb_layers = f"{RAW}/buildings/nsdmb_layers_economic_sectors.xlsx",
#         ports = f"{DATA}/networks/transport/port_polygon.gpkg",
#         airports = f"{DATA}/networks/transport/airport_polygon.gpkg",
#         residential_buidings = f"{RAW}/JAM_residential/jam_residential.shp",
#         known_building_assign = f"{RAW}/buildings/manual_building_assign.shp",
#         fishing_locations = f"{DATA}/land_type_and_use/aqua_farms.gpkg",
#         population = f"{DATA}/population/population_projections.gpkg",

#         #there is a layer_dict defined in the script that also seems to use the following:
#         trade_plants = f"{RAW}/buildings/nsdmb_tradeplants_layer_economic_sectors.xlsx",
#         exporters = f"{RAW}/buildings/nsdmb_exporters_layer_economic_sectors.xlsx",
#         industry = f"{RAW}/buildings/nsdmb_industry_layer_economic_sectors.xlsx",

#         #there are some cost shapefiles also in an array:
#         building_costs_1 = f"{RAW}/construction_permits/Construction Permit Mapping 2019-2020 FY/Construction_Permit_Mapping_Jan-March_Q4_2019-2020.shp",
#         building_costs_2 = f"{RAW}/construction_permits/Construction Permit Mapping 2019-2020 FY/Construction_Permits_October_-_December_(Q3)_2019-2020.shp",
#         building_costs_3 = f"{RAW}/construction_permits/Construction Permit Mapping 2019-2020 FY/Construction_Permits_Q1_2019_2020.shp",
#         building_costs_4 = f"{RAW}/construction_permits/Construction Permit Mapping 2019-2020 FY/Q2-2019- Construction Permits.shp",

#     params:
#         epsg = config["adaptation_options"]["epsg_jamaica"],
#         residential_min_area = 11.15, #perhaps should be added to config.yaml
#     output:
#         #there are some intermediary files that get generated (not sure if they have to be in output):
#         #incoming_data/buildings/buildings_assigned_economic_sectors_intermediate.gpkg
#         #incoming_data/buildings/commercial_buildings_assigned_economic_sectors_intermediate.gpkg
#         #incoming_data/hotosm_data/hotosm_jam_points_of_interest_gpkg/points_of_interest_assigned_economic_sectors_intermediate.gpkg
#         #incoming_data/buildings/building_attributes.csv
#         #incoming_data/buildings/buidling_sector_subsectors.csv
#         #incoming_data/buildings/building_cost_ranges.csv
#         result = f"{DATA}/buildings/buildings_assigned_economic_activity.gpkg"
        
#     shell:
#         """
#         python {input.script} \
#             --incoming-data {RAW} \
#             --data-dir {DATA} \
#             --epsg {epsg} \
#             --residential_min_area {residential_min_area} \


#         """

# rule buildings_sector_allocation:
#     """
#     The script associted with this rule SEEMS to functionally do something similar to the buildings data process rule
#     but it seems to be far simpler. Perhaps it was an earlier version?
#     """
#     input:
#         script = "workflow/1_context/buildings_sector_allocations.py",
#         buildings_input = f"{RAW}/buildings/jamaica-buildings.gpkg",
#         buildings_input_map = f"{RAW}/buildings/osm_building_column_mapping_economic_sectors.xlsx",
#         nsdmb_layers = f"{RAW}/buildings/nsdmb_layers_economic_sectors.xlsx",
#         trade_plants = f"{RAW}/buildings/nsdmb_tradeplants_layer_economic_sectors.xlsx",
#         exporters = f"{RAW}/buildings/nsdmb_exporters_layer_economic_sectors.xlsx",
#         industry = f"{RAW}/buildings/nsdmb_industry_layer_economic_sectors.xlsx",
#     params:
#         epsg = config["adaptation_options"]["epsg_jamaica"],
#     output:
#         unique_column_mapping = f"{RAW}/buildings/unique_column_mapping.xlsx",
#         #incoming_data/buildings/buildings_assigned_economic_sectors_intermediate.gpkg
#         #incoming_data/buildings/test_values.csv
#         #incoming_data/buildings/industry_points.csv
#         result = f"{DATA}/buildings/buildings_assigned_economic_sectors.gpkg"
#     shell:
#        """
#         python {input.script} \
#             --incoming-data {RAW} \
#             --data-dir {DATA} \
#             --epsg {epsg} \


#         """

# rule land_use_layers_process:
#     """
#     """
#     input:
#         script = "workflow/1_context/land_use_layers_process.py",
#         tnc_landuse = f"{RAW}/nsdmb/GWP_Jamaica_NSP_Master_Geodatabase_v01.gdb",
#         forest_landuse = f"{RAW}/Landuse 2013 data/2013_landuse_Landcover.shp",
#         mining_landuse = f"{RAW}/global_mining_areas/global_mining_polygons_v1.gpkg",
#         forest_sector_mapping = f"{DATA}/land_type_and_use/forest_classes_with_sector_mapping.csv",
#         tnc_sector_mapping = f"{DATA}/land_type_and_use/tnc_classes_with_sector_mapping.csv"
#     params:
#         epsg = config["adaptation_options"]["epsg_jamaica"],
#     output:
#         input_land_use_layers = f"{DATA}/land_type_and_use/input_land_use_layers.gpkg",
#         #land_use_modified = f"{DATA}/land_type_and_use/land_use_modified.gpkg",
#         jamaica_land_use_combined = f"{DATA}/land_type_and_use/jamaica_land_use_combined.gpkg",
#         #forest_classes = f"{DATA}/land_type_and_use/forest_classes.csv",
#         #tnc_classes = f"{DATA}/land_type_and_use/tnc_classes.csv",
#         jamaica_land_use_combined_with_sectors = f"{DATA}/land_type_and_use/jamaica_land_use_combined_with_sectors.gpkg",
#     shell:
#        """
#         python {input.script} \
#             --incoming-data {RAW} \
#             --data-dir {DATA} \
#             --epsg {epsg} \


#         """

# rule planning_layers:
#     """
#     """
#     input:
#         script = "workflow/1_context/planning_layers.py",
#         planning_layer_polygons = f"{RAW}/buildings/nsdmb_planning_layers_polygons.xlsx",
#         planning_layers = f"{RAW}/buildings/planning_layers.gpkg",
#         manchester_layers = f"{RAW}/buildings/land_use_layers_uses_codes.csv",
#         jamaica_parishes = f"{DATA}/boundaries/admin_boundaries.gpkg",

#         #there is an array that also defines the following files to be read:
#         clarendon_landuse_classes_with_sector_codes = f"{RAW}/buildings/clarendon_landuse_planning_classes_with_sector_codes.csv",
#         machester_landuse_classes_with_sector_codes = f"{RAW}/buildings/manchester_landuse_planning_classes_with_sector_codes.csv",
#         landuse_classes_with_sector_codes = f"{RAW}/buildings/landuse_classes_with_sector_codes.csv",
#     params:
#         epsg = config["adaptation_options"]["epsg_jamaica"],
#     output:
#         #landuse_planning_layers.gpkg = f"{RAW}/buildings/landuse_planning_layers.gpkg"
#         landuse_planning_layers_with_sectors = f"{RAW}/buildings/landuse_planning_layers_with_sectors.gpkg"
#     shell:
#        """
#         python {input.script} \
#             --incoming-data {RAW} \
#             --data-dir {DATA} \
#             --epsg {epsg} \


#         """