import os
import sys

def jamaica_sector_attributes():    
    sector_attributes = [
                            {
                                "sector_gpkg":"roads.gpkg",
                                "sector_label":"Roads",
                                "edge_layer":"edges",
                                "node_layer":"nodes",
                                "area_layer":None,
                                "edge_filter_column":"road_class",
                                "node_filter_column":"asset_type",
                                "area_filter_column":None,
                                "edge_categories":["CLASS A","CLASS B","CLASS C","METRO","TRACK","OTHER"],
                                "node_categories":["bridge"],
                                "area_categories":None,
                                "edge_categories_colors":["#000000","#6a51a3","#ce1256","#f16913","#fdae6b","#fdae6b"],
                                "node_categories_colors":["#800026"],
                                "area_categories_colors":None,
                                "edge_categories_labels":["CLASS A","CLASS B","CLASS C","METRO","TRACK/OTHER","TRACK/OTHER"],
                                "node_categories_labels":["BRIDGES"],
                                "area_categories_labels":None,
                                "edge_categories_linewidth":[1.0,1.0,1.0,1.0,1.0,1.0],
                                "edge_categories_zorder":[10,9,8,7,6,6],
                                "node_categories_markersize":[10.0],
                                "node_categories_marker":".",
                                "node_categories_zorder":[11],
                            },
                            {
                                "sector_gpkg":"rail.gpkg",
                                "sector_label":"Railways",
                                "edge_layer":"edges",
                                "node_layer":"nodes",
                                "area_layer":None,
                                "edge_filter_column":"status",
                                "node_filter_column":"asset_type",
                                "area_filter_column":None,
                                "edge_categories":["Functional","Non-Functional"],
                                "node_categories":["station"],
                                "area_categories":None,
                                "edge_categories_colors":["#238b45","#969696"],
                                "node_categories_colors":["#00441b"],
                                "area_categories_colors":None,
                                "edge_categories_labels":["Functional","Non-Functional"],
                                "node_categories_labels":["Station"],
                                "area_categories_labels":None,
                                "edge_categories_linewidth":[1.0,1.0],
                                "edge_categories_zorder":[10,10],
                                "node_categories_markersize":[10.0],
                                "node_categories_marker":["."],
                                "node_categories_zorder":[11],
                            },
                            {
                                "sector_gpkg":"port_polygon.gpkg",
                                "sector_label":"Ports",
                                "edge_layer":None,
                                "node_layer":None,
                                "area_layer":"areas",
                                "edge_filter_column":None,
                                "node_filter_column":None,
                                "area_filter_column":"asset_type",
                                "edge_categories":None,
                                "node_categories":None,
                                "area_categories":["ports"],
                                "edge_categories_colors":None,
                                "node_categories_colors":None,
                                "area_categories_colors":["#08306b"],
                                "edge_categories_labels":None,
                                "node_categories_labels":None,
                                "area_categories_labels":["PORT AREAS"],
                                "edge_categories_linewidth":None,
                                "edge_categories_zorder":None,
                                "node_categories_markersize":[15.0],
                                "node_categories_marker":["o"],
                                "node_categories_zorder":[11],
                            },
                            {
                                "sector_gpkg":"airport_polygon.gpkg",
                                "sector_label":"Airports",
                                "edge_layer":None,
                                "node_layer":None,
                                "area_layer":"areas",
                                "edge_filter_column":None,
                                "node_filter_column":None,
                                "area_filter_column":"asset_type",
                                "edge_categories":None,
                                "node_categories":None,
                                "area_categories":["airports"],
                                "edge_categories_colors":None,
                                "node_categories_colors":None,
                                "area_categories_colors":["#8c510a"],
                                "edge_categories_labels":None,
                                "node_categories_labels":None,
                                "area_categories_labels":["AIRPORT AREAS"],
                                "edge_categories_linewidth":None,
                                "edge_categories_zorder":None,
                                "node_categories_markersize":[15.0],
                                "node_categories_marker":["o"],
                                "node_categories_zorder":[11],
                            },
                            # {
                            #     "sector_gpkg":"electricity_network_v1.0.gpkg",
                            #     "sector_label":"Energy",
                            #     "edge_layer":"edges",
                            #     "node_layer":"nodes",
                            #     "area_layer":None,
                            #     "edge_filter_column":"voltage",
                            #     "node_filter_column":"subtype",
                            #     "area_filter_column":None,
                            #     "edge_categories":["138kV","69 kV","24 kV","12 kV"],
                            #     "node_categories":["diesel","gas","hydro","solar","wind",
                            #                     "substation","pole","demand"],
                            #     "area_categories":None,
                            #     "edge_categories_colors":["#000000","#1f78b4","#33a02c","#f16913"],
                            #     "node_categories_colors":["#800026","#800026","#800026","#800026","#800026",
                            #                                 "#6a51a3","#ce1256","#f16913"],
                            #     "area_categories_colors":None,
                            #     "edge_categories_labels":["138kV","69kV","24kV","12kV"],
                            #     "node_categories_labels":["Power plant","Power plant",
                            #                             "Power plant","Power plant",
                            #                             "Power plant",
                            #                             "Substation",
                            #                             "Pole","Demand point"],
                            #     "area_categories_labels":None,
                            #     "edge_categories_linewidth":[1.0,1.0,1.0,1.0],
                            #     "edge_categories_zorder":[10,9,8,7],
                            #     "node_categories_markersize":[15.0,15.0,15.0,15.0,15.0,10.0,4.0,4.0],
                            #     "node_categories_marker":["s","s","s","s","s","o",".","."],
                            #     "node_categories_zorder":[20,20,20,20,20,19,18,17],
                            # },
                            {
                                "sector_gpkg":"electricity_network_v1.0.gpkg",
                                "sector_label":"Energy",
                                "edge_layer":"edges",
                                "node_layer":"nodes",
                                "area_layer":None,
                                "edge_filter_column":"voltage",
                                "node_filter_column":"subtype",
                                "area_filter_column":None,
                                "edge_categories":["138kV","69 kV","24 kV","12 kV"],
                                "node_categories":["diesel","gas","hydro","solar","wind",
                                                "substation"],
                                "area_categories":None,
                                "edge_categories_colors":["#000000","#006d2c","#41ab5d","#66c2a4"],
                                "node_categories_colors":["#800026","#800026","#800026","#800026","#800026",
                                                            "#6a51a3"],
                                "area_categories_colors":None,
                                "edge_categories_labels":["138kV lines","69kV lines","24kV lines","12kV lines"],
                                "node_categories_labels":["Power plants","Power plants",
                                                        "Power plants","Power plants",
                                                        "Power plants",
                                                        "Substations"
                                                        ],
                                "area_categories_labels":None,
                                "edge_categories_linewidth":[1.5,1.0,0.8,0.8],
                                "edge_categories_zorder":[10,9,8,7],
                                "node_categories_markersize":[15.0,15.0,15.0,15.0,15.0,15.0],
                                "node_categories_marker":["s","s","s","s","s","o"],
                                "node_categories_zorder":[15,15,15,15,15,15],
                            },
                            {
                                "sector_gpkg":"", # We will integrate the NWC layers together for this
                                "sector_label":"Potable water",
                                "edge_layer":"edges",
                                "node_layer":"nodes",
                                "area_layer":None,
                                "edge_filter_column":"asset",
                                "node_filter_column":"asset_type",
                                "area_filter_column":None,
                                "edge_categories":["pipeline"],
                                "node_categories":["Booster Station","Catchment","Entombment",
                                                    "Filter Plant","Intake",
                                                    "Production Well","Pump Station",
                                                    "Relift Station","Reservoir",
                                                    "River Source","Spring","Storage Tank",
                                                    "Sump","Treatment Plant"],
                                "area_categories":None,
                                "edge_categories_colors":["#ec7014"],
                                "node_categories_colors":["#807dba",
                                                            "#6a51a3",
                                                            "#54278f",
                                                            "#3f007d",
                                                            "#4292c6",
                                                            "#2171b5",
                                                            "#08519c",
                                                            "#08306b",
                                                            "#41ab5d",
                                                            "#238b45",
                                                            "#006d2c",
                                                            "#00441b",
                                                            "#d94801",
                                                            "#a63603",
                                                            "#7f2704"
                                                            ],
                                "area_categories_colors":None,
                                "edge_categories_labels":["Pipelines"],
                                "node_categories_labels":["Booster Station","Catchment","Entombment",
                                                            "Filter Plant","Intake",
                                                            "Production Well","Pump Station",
                                                            "Relift Station","Reservoir",
                                                            "River Source","Spring","Storage Tank",
                                                            "Sump","Treatment Plant"],
                                "area_categories_labels":None,
                                "edge_categories_linewidth":[0.5],
                                "edge_categories_zorder":[10],
                                "node_categories_markersize":[6.0,6.0,6.0,
                                                                6.0,6.0,6.0,
                                                                6.0,6.0,6.0,
                                                                6.0,6.0,6.0,
                                                                6.0,6.0,6.0],
                                "node_categories_marker":["o","s","8",
                                                        "p","h","H",
                                                        "D","d","s",
                                                        ".","d","H",
                                                        "s","h","o"],
                                "node_categories_zorder":[15,15,15,
                                                            15,15,15,
                                                            15,15,15,
                                                            15,15,15,
                                                            15,15,15],
                            },
                            {
                                "sector_gpkg":"irrigation_assets_NIC.gpkg",
                                "sector_label":"Irrigation",
                                "edge_layer":"edges",
                                "node_layer":"nodes",
                                "area_layer":None,
                                "edge_filter_column":"asset_type",
                                "node_filter_column":"asset_type",
                                "area_filter_column":None,
                                "edge_categories":["canal","pipeline"],
                                "node_categories":["well"],
                                "area_categories":None,
                                "edge_categories_colors":["#016c59","#3690c0"],
                                "node_categories_colors":["#014636"],
                                "area_categories_colors":None,
                                "edge_categories_labels":["Canals","Pipelines"],
                                "node_categories_labels":["Wells"
                                                        ],
                                "area_categories_labels":None,
                                "edge_categories_linewidth":[0.8,0.8],
                                "edge_categories_zorder":[10,10],
                                "node_categories_markersize":[10.0],
                                "node_categories_marker":["o"],
                                "node_categories_zorder":[15],
                            },
                            {
                                "sector_gpkg":"waste_water_facilities_NWC.gpkg",
                                "sector_label":"Wastewater Treatment",
                                "edge_layer":None,
                                "node_layer":"nodes",
                                "area_layer":None,
                                "edge_filter_column":None,
                                "node_filter_column":"asset_type",
                                "area_filter_column":None,
                                "edge_categories":None,
                                "node_categories":["Sump","WW Pump Station","WW Relift Station","WW Treatment Plant"],
                                "area_categories":None,
                                "edge_categories_colors":None,
                                "node_categories_colors":["#bfd3e6",
                                                    "#4d004b",
                                                    "#88419d",
                                                    "#ef3b2c"],
                                "area_categories_colors":None,
                                "edge_categories_labels":None,
                                "node_categories_labels":["Sump","Pumping Station","Relift Station","Treatment Plant"],
                                "area_categories_labels":None,
                                "edge_categories_linewidth":None,
                                "edge_categories_zorder":None,
                                "node_categories_markersize":[12.0,12.0,12.0,12.0],
                                "node_categories_marker":[".","^","s","o"],
                                "node_categories_zorder":[15,15,15,15],
                            },

                        ]

    return sector_attributes